# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  one:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: echo "hello world one"
      - run: mkdir -p my_workspace
      - run: echo "trying out workspace" > my_workspace/echo-output
      - persist_to_workspace:
        root: my_workspace
        paths:
          - echo-workspace

  two:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: echo "hello world two"
      - attach_workspace:
          at: my_workspace
      - run: echo "test"

workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two